### ISSUE TITLE
Fail to move utra robot with function "moveto_servo_joint"

### ISSUE THREAD

**Issue by gmp-prem** [UmbraTek/ut_sdk_cpp#1]
I try using the ut_sdk for both cpp and python and found the same error
The demo01_report and demo03_motion_joint_space_p2p worked fine
I could read robot joint state and move the robot with "moveto_joint_p2p".
but when I try demo08_motion_servo_joint the robot fail to execute "moveto_servo_joint" function and return this error

![image](https://user-images.githubusercontent.com/47204875/147460088-75b70274-ff82-49ca-a938-32869d9ecc82.png)

could you help me what could be the reason?

**Comment by UmbraTek** [comment]
you need to upgrade the controller of Utra

**Comment by gmp-prem** [comment]
Thank you for the reply.
Could you tell me how to upgrade controller?

**Comment by samping** [comment]
you can open and connect the studio,  go to the setting , find controller , check upgrade and download the firmware, reboot the Utra
![image](https://user-images.githubusercontent.com/6119267/147462242-01b715d0-8c1f-4a41-84c1-dfd86f807bbe.png)

**Comment by gmp-prem** [comment]
thank you. it fixed.
